filebeat.modules:
  - module: elasticsearch
  - module: logstash
filebeat.inputs:
  - type: log
    paths:
      - /var/www/data/*.log
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
setup.kibana:
  host: "kibana:5601"
